name: Java CI with Gradle

on:
    workflow_dispatch:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

permissions:
    contents: read

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 20
                uses: actions/setup-java@v4
                with:
                    java-version: '20'
                    distribution: 'temurin'
            -   name: Setup and execute Gradle 'test' task
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: test
